### ISSUE TITLE
Update of sensor is taking over 10 seconds

### ISSUE THREAD

**Issue by xldude** [zacs/ha-gtfs-rt#10]
Hello,

I'm trying to setup the gtfs-rt for the first time in my HA.
It can obviously fetch some data from the API but the information it shows is late
* I have checked the system time is correct 
* it shows _'due at'_ and _'next bus'_ time stamps correctly but _'due at'_ is in history
* _'due in'_ is always +/- 60 min though the line has bus every +/- 10 min.

**Log shows me following warning** 
```
WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.570_at_airport is taking over 10 seconds
```
**sensor config**

```
sensor:
  - platform: gtfs_rt
    trip_update_url: 'https://realtime.hsl.fi/realtime/trip-updates/v2/hsl'
    vehicle_position_url: 'https://realtime.hsl.fi/realtime/vehicle-positions/v2/hsl'
    departures:
    - name: "570 at airport"
      route: 4570
      stopid: 4530259
```

Any idea how to fix this? All ideas would be appreciated.
