### ISSUE TITLE
Unable to set up with NYC MTA or Austin feeds, entities not created

### ISSUE THREAD

**Issue by grischard** [zacs/ha-gtfs-rt#15]
I am trying to configure gtfs_rt f6f260c on Home Assistant 2022.4.0, running on Home Assistant OS. I don't see any integration, device or entity getting created, and don't see any relevant messages in the debug logs. What am I doing wrong?

My config is copy-pasted from the README for troubleshooting:

```yaml
logger:
  logs:
    custom_components.gtfs_rt: debug
sensor:
  - platform: gtfs_rt
    trip_update_url: "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-bdfm"
    x_api_key: (my key from https://api.mta.info/#/AccessKey)
    departures:
      - name: "Brooklyn F"
        route: "F"
        stopid: "F16S"
```

The log entries containing that look relevant are:

2022-04-06 23:53:23 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.gtfs_rt
2022-04-06 23:53:28 DEBUG (MainThread) [homeassistant.bootstrap] Integration remaining: { […] 'sensor.gtfs_rt': 4.80698, […]}
2022-04-06 23:53:40 DEBUG (MainThread) [homeassistant.helpers.translation] Cache miss for en-GB: binary_sensor.hassio, input_number, binary_sensor.ble_monitor, sensor.gtfs_rt, weather, input_datetime, media_player, sensor.thermal_comfort
2022-04-06 23:53:41 DEBUG (SyncWorker_0) [homeassistant.util.json] JSON file not found: /config/custom_components/gtfs_rt/translations/sensor.en-GB.json
2022-04-06 23:53:41 DEBUG (SyncWorker_6) [homeassistant.util.json] JSON file not found: /config/custom_components/gtfs_rt/translations/sensor.en.json
2022-04-06 23:54:10 DEBUG (MainThread) [homeassistant.bootstrap] Integration setup times: {[…] 'gtfs_rt': 8.659741, […]}
2022-04-06 23:54:39 DEBUG (MainThread) [custom_components.hacs] <Integration zacs/ha-gtfs-rt> Getting repository information
2022-04-06 23:54:43 DEBUG (MainThread) [custom_components.hacs] <Integration zacs/ha-gtfs-rt> Running checks against master

I have:

- verified manually with `curl` that my api key and trip update url are valid.
- setting the `trip_update_url` to an URL I control, to make sure that the http requests are being made.
- setting the config to the Austin, Texas example in the README
-  Trying the gtfs_realtime_pb2 example code to make sure it can get `trip_update`s from both the Austin and the NYC feeds
-  I am not sure what to do next. Puzzled, really.
