### ISSUE TITLE
See following departures

### ISSUE THREAD

**Issue by DaAwesomeP** [zacs/ha-gtfs-rt#35]
Hello!

Would it be possible to have multiple entities for one route/stop combination to show the next and following departure? This is very useful for "I won't make the train coming in 2 minutes, but I will make the one coming in 10 minutes."

There could possibly be an `offset` options that is `0` by default but will show the following arrival when set to `1` or the third arrival when set to `2`.

**Comment by DaAwesomeP** [comment]
Aha! I figured out that there is the "Next bus in" attribute. Note that this maybe should be "next arrival in" since it could be a bus or train or other vehicle.

It still would be nice to have a way to see the 3rd arrival.

Example for dashboard:
```yaml
type: entities
entities:
  - entity: sensor.my_route_and_stop
  - type: attribute
    entity: sensor.my_route_and_stop
    attribute: Next bus due in
    name: Following train
    suffix: min
state_color: false
title: Trains
```
